### ISSUE TITLE
Could not start today after update ...

### ISSUE THREAD

**Issue by MailFranzel** [netbrain/zwift#55] opened 2024-01-01 17:20 UTC
Yesterday it was fine. But today after a update of the container it is not running anymore!
![Screenshot_20240101_181706](https://github.com/netbrain/zwift/assets/47360315/e3d787b6-78ea-4faf-ba95-6d4bc9f8f424)

After this the program stops running.

**Comment by netbrain** [comment] 2024-01-01 17:57
dupe of #54

**Closed by netbrain** 2024-01-01 17:57 UTC
